/**
 * @dev QQ Score dimension definitions, category metadata, and raw asset data.
 */

// PUBLIC

export type DimKey = "macro" | "fund" | "token" | "chain" | "tech"
export type SortKey = DimKey | "comp"

export interface Dimension {
   key: SortKey
   label: string
   short: string
   weight: number
   color: string
   /** @dev Whether this dimension is selectable in the current build */
   enabled: boolean
}

export interface Category {
   l: string
   c: string
}

export type CatKey = "sov" | "l1" | "l2" | "defi" | "pay" | "cex" | "meme" | "infra" | "ai" | "rwa" | "lsd" | "game"

export type TimeframeKey = "daily" | "weekly" | "monthly" | "yearly"

export interface Timeframe {
   key: TimeframeKey
   label: string
   short: string
   /** @dev Whether this timeframe is accessible in the current build */
   enabled: boolean
   /** @dev Dimension weights for this timeframe (must sum to 1.0) */
   weights: Record<DimKey, number>
}

/**
 * @dev Timeframe definitions with per-dimension weights from QQ Omega architecture.
 * QQ Score = sum(dimension_score * timeframe_weight) per timeframe.
 * Short-term timeframes weight Technical/On-Chain heavier; long-term weights Macro/Fundamentals.
 */
export const TIMEFRAMES: Timeframe[] = [
   {
      key: "yearly",
      label: "Yearly - Holder",
      short: "1Y",
      enabled: true,
      weights: { macro: 0.3, fund: 0.35, token: 0.2, chain: 0.1, tech: 0.05 },
   },
   {
      key: "monthly",
      label: "Monthly - Swing",
      short: "1M",
      enabled: false,
      weights: { macro: 0.2, fund: 0.3, token: 0.25, chain: 0.15, tech: 0.1 },
   },
   {
      key: "weekly",
      label: "Weekly - Tactical",
      short: "1W",
      enabled: false,
      weights: { macro: 0.1, fund: 0.2, token: 0.25, chain: 0.25, tech: 0.2 },
   },
   {
      key: "daily",
      label: "Daily - Scalper",
      short: "1D",
      enabled: false,
      weights: { macro: 0.1, fund: 0.1, token: 0.2, chain: 0.3, tech: 0.3 },
   },
]

export interface RawAsset {
   s: string
   n: string
   cat: CatKey
   macro: number
   fund: number
   token: number
   chain: number
   tech: number
   note: string
}

export interface RankedAsset extends RawAsset {
   comp: number
   rank: number
   qq: number
}

export const DIMS: Dimension[] = [
   { key: "comp", label: "QQ Score", short: "QQ", weight: 1, color: "#fd015a", enabled: true },
   { key: "macro", label: "Macro", short: "MAC", weight: 0.2, color: "#ff4d94", enabled: false },
   { key: "fund", label: "Fundamentals", short: "FND", weight: 0.2, color: "#ffd700", enabled: false },
   { key: "token", label: "Tokenomics", short: "TKN", weight: 0.25, color: "#66d9ff", enabled: false },
   { key: "chain", label: "On-Chain", short: "OCH", weight: 0.2, color: "#b388ff", enabled: false },
   { key: "tech", label: "Technical", short: "TEC", weight: 0.15, color: "#69f0ae", enabled: false },
]

/** @dev Only the actual scoring dimensions (excludes QQ composite). Used by composite(). */
export const SCORE_DIMS = DIMS.filter((d): d is Dimension & { key: DimKey } => d.key !== "comp")

export const CATS: Record<CatKey, Category> = {
   sov: { l: "Store of Value", c: "#ffd700" },
   l1: { l: "L1", c: "#b388ff" },
   l2: { l: "L2", c: "#ff6b6b" },
   defi: { l: "DeFi", c: "#66d9ff" },
   pay: { l: "Payments", c: "#69f0ae" },
   cex: { l: "Exchange", c: "#ff4d94" },
   meme: { l: "Meme", c: "#ffab40" },
   infra: { l: "Infra", c: "#80cbc4" },
   ai: { l: "AI", c: "#ea80fc" },
   rwa: { l: "RWA", c: "#a1887f" },
   lsd: { l: "Liquid Staking", c: "#ffcc80" },
   game: { l: "Gaming", c: "#f48fb1" },
}

export const RAW: RawAsset[] = [
   {
      s: "BTC",
      n: "Bitcoin",
      cat: "sov",
      macro: 97,
      fund: 72,
      token: 93,
      chain: 88,
      tech: 82,
      note: "Ultimate store of value. 21M hard cap.",
   },
   {
      s: "ETH",
      n: "Ethereum",
      cat: "l1",
      macro: 82,
      fund: 95,
      token: 78,
      chain: 92,
      tech: 68,
      note: "Dominant L1. EIP-1559 burn.",
   },
   {
      s: "HYPE",
      n: "Hyperliquid",
      cat: "cex",
      macro: 42,
      fund: 88,
      token: 88,
      chain: 88,
      tech: 78,
      note: "Buyback model. No VC. Perp DEX #1.",
   },
   {
      s: "SOL",
      n: "Solana",
      cat: "l1",
      macro: 58,
      fund: 82,
      token: 55,
      chain: 80,
      tech: 80,
      note: "High TPS. Firedancer. DeFi hub.",
   },
   {
      s: "AAVE",
      n: "Aave",
      cat: "defi",
      macro: 45,
      fund: 85,
      token: 72,
      chain: 82,
      tech: 70,
      note: "Lending king. GHO. Multi-chain.",
   },
   {
      s: "BNB",
      n: "BNB",
      cat: "cex",
      macro: 55,
      fund: 70,
      token: 74,
      chain: 65,
      tech: 68,
      note: "Binance ecosystem. Auto-burn.",
   },
   {
      s: "MKR",
      n: "Maker",
      cat: "defi",
      macro: 48,
      fund: 80,
      token: 78,
      chain: 70,
      tech: 60,
      note: "DAI. RWA yield. Buyback.",
   },
   {
      s: "LINK",
      n: "Chainlink",
      cat: "infra",
      macro: 52,
      fund: 85,
      token: 48,
      chain: 68,
      tech: 62,
      note: "Oracle monopoly. CCIP.",
   },
   {
      s: "PENDLE",
      n: "Pendle",
      cat: "defi",
      macro: 30,
      fund: 72,
      token: 70,
      chain: 68,
      tech: 65,
      note: "Yield trading. vePENDLE.",
   },
   {
      s: "JUP",
      n: "Jupiter",
      cat: "defi",
      macro: 28,
      fund: 68,
      token: 62,
      chain: 72,
      tech: 60,
      note: "Solana DEX king. ASR.",
   },
   {
      s: "XRP",
      n: "Ripple",
      cat: "pay",
      macro: 62,
      fund: 58,
      token: 35,
      chain: 52,
      tech: 70,
      note: "Banks. Bad tokenomics.",
   },
   {
      s: "ENA",
      n: "Ethena",
      cat: "defi",
      macro: 28,
      fund: 65,
      token: 50,
      chain: 62,
      tech: 58,
      note: "USDe synthetic dollar.",
   },
   {
      s: "INJ",
      n: "Injective",
      cat: "l1",
      macro: 22,
      fund: 42,
      token: 60,
      chain: 32,
      tech: 45,
      note: "Weekly burn is real. TVL tiny. More hype than substance.",
   },
   {
      s: "UNI",
      n: "Uniswap",
      cat: "defi",
      macro: 40,
      fund: 80,
      token: 45,
      chain: 78,
      tech: 58,
      note: "DEX king. No value accrual.",
   },
   {
      s: "AVAX",
      n: "Avalanche",
      cat: "l1",
      macro: 35,
      fund: 48,
      token: 48,
      chain: 38,
      tech: 48,
      note: "Subnets underused. RWA narrative. TVL bleeding vs ETH/SOL.",
   },
   {
      s: "SUI",
      n: "Sui",
      cat: "l1",
      macro: 28,
      fund: 50,
      token: 32,
      chain: 42,
      tech: 65,
      note: "Move VM. VC unlock heavy. Tech decent, adoption thin.",
   },
   {
      s: "CRV",
      n: "Curve",
      cat: "defi",
      macro: 25,
      fund: 65,
      token: 55,
      chain: 58,
      tech: 42,
      note: "Stableswap. veCRV.",
   },
   {
      s: "RAY",
      n: "Raydium",
      cat: "defi",
      macro: 18,
      fund: 52,
      token: 55,
      chain: 58,
      tech: 48,
      note: "Solana AMM. Buyback.",
   },
   {
      s: "RUNE",
      n: "THORChain",
      cat: "defi",
      macro: 22,
      fund: 55,
      token: 52,
      chain: 48,
      tech: 40,
      note: "Cross-chain swaps.",
   },
   {
      s: "ADA",
      n: "Cardano",
      cat: "l1",
      macro: 32,
      fund: 28,
      token: 58,
      chain: 22,
      tech: 42,
      note: "Fair launch, no VC. But ghost chain - almost zero real usage.",
   },
   {
      s: "STX",
      n: "Stacks",
      cat: "l1",
      macro: 35,
      fund: 48,
      token: 50,
      chain: 38,
      tech: 52,
      note: "Bitcoin L2. sBTC. Very early.",
   },
   {
      s: "LDO",
      n: "Lido",
      cat: "lsd",
      macro: 30,
      fund: 62,
      token: 42,
      chain: 55,
      tech: 38,
      note: "Liquid staking dominant.",
   },
   {
      s: "DOGE",
      n: "Dogecoin",
      cat: "meme",
      macro: 48,
      fund: 20,
      token: 30,
      chain: 42,
      tech: 55,
      note: "Meme king. Inflationary.",
   },
   {
      s: "DOT",
      n: "Polkadot",
      cat: "l1",
      macro: 25,
      fund: 35,
      token: 38,
      chain: 28,
      tech: 32,
      note: "Parachains dead. JAM is a hail mary. Treasury bleeding.",
   },
   {
      s: "ATOM",
      n: "Cosmos",
      cat: "infra",
      macro: 25,
      fund: 40,
      token: 35,
      chain: 32,
      tech: 35,
      note: "IBC is useful. ATOM token captures zero ecosystem value.",
   },
   {
      s: "TIA",
      n: "Celestia",
      cat: "infra",
      macro: 28,
      fund: 60,
      token: 32,
      chain: 42,
      tech: 45,
      note: "DA layer. VC unlock.",
   },
   {
      s: "OP",
      n: "Optimism",
      cat: "l2",
      macro: 32,
      fund: 55,
      token: 38,
      chain: 48,
      tech: 42,
      note: "Superchain. Parasite.",
   },
   {
      s: "ARB",
      n: "Arbitrum",
      cat: "l2",
      macro: 32,
      fund: 58,
      token: 35,
      chain: 55,
      tech: 40,
      note: "L2 TVL king. No value.",
   },
   {
      s: "FET",
      n: "Fetch.ai",
      cat: "ai",
      macro: 30,
      fund: 50,
      token: 42,
      chain: 40,
      tech: 58,
      note: "AI agent infra.",
   },
   {
      s: "ONDO",
      n: "Ondo",
      cat: "rwa",
      macro: 35,
      fund: 55,
      token: 38,
      chain: 42,
      tech: 52,
      note: "RWA. BlackRock.",
   },
   {
      s: "RENDER",
      n: "Render",
      cat: "ai",
      macro: 28,
      fund: 52,
      token: 45,
      chain: 38,
      tech: 55,
      note: "GPU compute.",
   },
   {
      s: "GRT",
      n: "The Graph",
      cat: "infra",
      macro: 22,
      fund: 55,
      token: 40,
      chain: 48,
      tech: 42,
      note: "Indexing. Dilutive.",
   },
   {
      s: "JTO",
      n: "Jito",
      cat: "defi",
      macro: 18,
      fund: 50,
      token: 38,
      chain: 52,
      tech: 45,
      note: "Solana MEV.",
   },
   {
      s: "TRX",
      n: "Tron",
      cat: "pay",
      macro: 28,
      fund: 32,
      token: 28,
      chain: 45,
      tech: 32,
      note: "USDT highway only. Justin Sun centralized. No innovation.",
   },
   {
      s: "TON",
      n: "Toncoin",
      cat: "l1",
      macro: 28,
      fund: 38,
      token: 25,
      chain: 38,
      tech: 35,
      note: "Telegram integration. Shallow DeFi. Mini apps unproven.",
   },
   {
      s: "AERO",
      n: "Aerodrome",
      cat: "defi",
      macro: 12,
      fund: 48,
      token: 55,
      chain: 52,
      tech: 45,
      note: "Base DEX. veAERO.",
   },
   {
      s: "TAO",
      n: "Bittensor",
      cat: "ai",
      macro: 25,
      fund: 65,
      token: 55,
      chain: 52,
      tech: 65,
      note: "Decentralized AI subnets. Unique compute. No VC. Strong AI cycle momentum.",
   },
   {
      s: "KAS",
      n: "Kaspa",
      cat: "l1",
      macro: 15,
      fund: 22,
      token: 50,
      chain: 25,
      tech: 48,
      note: "DAG PoW. Fair launch. Near zero adoption.",
   },
   {
      s: "FIL",
      n: "Filecoin",
      cat: "infra",
      macro: 22,
      fund: 45,
      token: 35,
      chain: 38,
      tech: 42,
      note: "Storage. Inflation.",
   },
   {
      s: "NEAR",
      n: "Near",
      cat: "l1",
      macro: 22,
      fund: 40,
      token: 35,
      chain: 32,
      tech: 40,
      note: "Chain abstraction narrative. Low real adoption.",
   },
   {
      s: "SEI",
      n: "Sei",
      cat: "l1",
      macro: 15,
      fund: 28,
      token: 28,
      chain: 22,
      tech: 42,
      note: "Parallelized EVM. Nobody uses it.",
   },
   {
      s: "PYTH",
      n: "Pyth",
      cat: "infra",
      macro: 20,
      fund: 48,
      token: 30,
      chain: 40,
      tech: 42,
      note: "Solana oracle.",
   },
   {
      s: "MATIC",
      n: "Polygon",
      cat: "l2",
      macro: 28,
      fund: 45,
      token: 32,
      chain: 38,
      tech: 35,
      note: "POL. Identity crisis.",
   },
   {
      s: "DYDX",
      n: "dYdX",
      cat: "defi",
      macro: 18,
      fund: 48,
      token: 42,
      chain: 45,
      tech: 38,
      note: "Perp DEX. Staking from revenue.",
   },
   {
      s: "BANANA",
      n: "Banana Gun",
      cat: "defi",
      macro: 12,
      fund: 58,
      token: 88,
      chain: 62,
      tech: 55,
      note: "Trading bot. Revenue -> auto buyback & burn. No VC. 97% circ. Token needed for bot access. Revenue machine.",
   },
   {
      s: "GMX",
      n: "GMX",
      cat: "defi",
      macro: 15,
      fund: 55,
      token: 78,
      chain: 52,
      tech: 48,
      note: "Perp DEX OG. 30% fees to GMX stakers. No VC. 93% circ. esGMX vesting. Real yield pioneer.",
   },
   {
      s: "GNO",
      n: "Gnosis",
      cat: "infra",
      macro: 22,
      fund: 60,
      token: 75,
      chain: 48,
      tech: 42,
      note: "Gnosis Chain validators need GNO. Active buyback from treasury. OG fair distro. 95% circ.",
   },
   {
      s: "LQTY",
      n: "Liquity",
      cat: "defi",
      macro: 10,
      fund: 52,
      token: 82,
      chain: 45,
      tech: 40,
      note: "100% circulating. Liquidation + borrowing revenue to stakers. Zero governance. Pure utility. V2 incoming.",
   },
   {
      s: "CVX",
      n: "Convex",
      cat: "defi",
      macro: 10,
      fund: 50,
      token: 72,
      chain: 48,
      tech: 35,
      note: "vlCVX = Curve voting power. Earns bribes. No VC. 88% circ. Curve wars kingmaker.",
   },
   {
      s: "YFI",
      n: "Yearn",
      cat: "defi",
      macro: 12,
      fund: 48,
      token: 80,
      chain: 42,
      tech: 38,
      note: "veYFI buyback model. No VC. 100% circ. 36k fixed supply. Vault yield utility. OG DeFi.",
   },
]

export const TOTAL = RAW.length
